services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_task
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
        - pgadmin_data:/var/lib/pgadmin
        - ./servers.json:/pgadmin4/servers.json
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data:

